In [1]:
!pip install certifi
import certifi

Requirement already satisfied: certifi in e:\ams docs\courses\guvi\data science\projects\04_airbnb project\airbnb_code\.venv\lib\site-packages (2024.7.4)

In [2]:
import pymongo
import pandas as pd
import numpy as np
import streamlit as st
from streamlit_option_menu import option_menu
from collections import Counter

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import plotly.express as px
import nbformat
import seaborn as sns

In [4]:
# Connection to Mongo DB 
# Database - "Airbnb_DB"

client=pymongo.MongoClient("mongodb+srv://sowmiyaamgs:1234@cluster0.hwjrmfq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",tlsCAFile=certifi.where())
db=client["Airbnb_DB"]

In [5]:
# Collection - "Airbnb_Info" : Fetching all documents and storing as a list - then converting into DF

record=db["Airbnb_Info"]
data = []
docs = list(record.find())
for doc in docs:
    data.append(doc)
df = pd.DataFrame(data)

In [6]:
df.head(2)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,10038496,https://www.airbnb.com/rooms/10038496,Copacabana Apartment Posto 6,"The Apartment has a living room, toilet, bedro...","The apartment has a living room, wash room, su...","The Apartment has a living room, toilet, bedro...",Copacabana in the South zone is the district t...,,On the street there is plenty of transport and...,todo o espaço.,...,3,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51530266', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 7, 'availability_60': 19, ...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '60037020', 'date': '2016-01-18 05:00...",NaN,NaN,NaN
1,10140368,https://www.airbnb.com/rooms/10140368,A bedroom far away from home,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...",our place is a good sized apartment in a very ...,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...","our neighborhood is basically peaceful, there ...",,subway is about 5-8 minutes away by foot. ther...,you can use the living room and kitchen. we al...,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '1017772', 'host_url': 'https://ww...","{'street': 'Queens, NY, United States', 'subur...","{'availability_30': 20, 'availability_60': 29,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '59098822', 'date': '2016-01-06 05:00...",NaN,NaN,NaN

In [7]:
# df_host => 5555 * 16 columns

df_host = pd.json_normalize(df["host"])
df_host

,host_id,host_url,host_name,host_location,host_about,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,51530266,https://www.airbnb.com/users/show/51530266,Ana Valéria,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Professora de Educação Física formada pela uni...,within an hour,https://a0.muscache.com/im/pictures/8c7bb5fe-7...,https://a0.muscache.com/im/pictures/8c7bb5fe-7...,Copacabana,100.0,True,True,True,2,2,"[email, phone, reviews, jumio, government_id]"
1,1017772,https://www.airbnb.com/users/show/1017772,Lane,US,Hello. I am a very passionate person with what...,within an hour,https://a0.muscache.com/im/pictures/user/0a118...,https://a0.muscache.com/im/pictures/user/0a118...,Jamaica,100.0,True,True,True,1,1,"[email, phone, manual_online, facebook, review..."
2,52004703,https://www.airbnb.com/users/show/52004703,Mehmet Emin,"Istanbul, İstanbul, Turkey",,within a few hours,https://a0.muscache.com/im/pictures/user/4cb6b...,https://a0.muscache.com/im/pictures/user/4cb6b...,,100.0,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, offli..."
3,2649859,https://www.airbnb.com/users/show/2649859,Elisabete,"Porto, Porto, Portugal","Sou activa, responsável, interessada por leitu...",NaN,https://a0.muscache.com/im/pictures/3e7725d5-7...,https://a0.muscache.com/im/pictures/3e7725d5-7...,,NaN,False,True,True,2,2,"[email, phone, reviews, jumio, government_id]"
4,13764143,https://www.airbnb.com/users/show/13764143,Ben,"New South Wales, Australia","Software developer from Sydney, Australia.",NaN,https://a0.muscache.com/im/pictures/03c4d82b-7...,https://a0.muscache.com/im/pictures/03c4d82b-7...,Surry Hills,NaN,False,True,True,1,1,"[email, phone, google, reviews, jumio, offline..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,51142039,https://www.airbnb.com/users/show/51142039,Dailton,"Rio de Janeiro, State of Rio de Janeiro, Brazil","Um bairro tranquilo, de facil acesso para outr...",within a few hours,https://a0.muscache.com/im/pictures/user/ad3e9...,https://a0.muscache.com/im/pictures/user/ad3e9...,Rio Comprido,100.0,False,True,False,3,3,"[email, phone, reviews]"
5551,35533112,https://www.airbnb.com/users/show/35533112,Benjamin,"Montreal, Québec, Canada",,NaN,https://a0.muscache.com/im/pictures/4f579b54-9...,https://a0.muscache.com/im/pictures/4f579b54-9...,Downtown Montreal,NaN,False,True,False,1,1,"[email, phone, reviews]"
5552,37776205,https://www.airbnb.com/users/show/37776205,Ana,Portugal,"Não poderia viver sem sol, boas amizades e dor...",within an hour,https://a0.muscache.com/im/users/37776205/prof...,https://a0.muscache.com/im/users/37776205/prof...,,100.0,True,True,False,8,8,"[email, phone, reviews, offline_government_id,..."
5553,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",,NaN,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,,NaN,False,True,False,1,1,"[email, phone]"
5554,2296185,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,within a few hours,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,,90.0,False,True,True,3,3,"[email, phone, reviews, jumio, offline_governm..."

In [8]:
# df_address => 5555 * 9 columns

df_address = pd.json_normalize(df["address"])
df_address

,street,suburb,government_area,market,country,country_code,location.type,location.coordinates,location.is_location_exact
0,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,"[-43.190849194463404, -22.984339360067814]",False
1,"Queens, NY, United States",Queens,Briarwood,New York,United States,US,Point,"[-73.82257, 40.71485]",True
2,"Fatih , İstanbul, Turkey",Fatih,Fatih,Istanbul,Turkey,TR,Point,"[28.98009, 41.0062]",False
3,"Porto, Porto, Portugal",,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,"[-8.60867, 41.1543]",False
4,"Surry Hills, NSW, Australia",Darlinghurst,Sydney,Sydney,Australia,AU,Point,"[151.21554, -33.88029]",True
...,...,...,...,...,...,...,...,...,...
5550,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Tijuca,Rio Comprido,Rio De Janeiro,Brazil,BR,Point,"[-43.21066664661915, -22.918154868570046]",False
5551,"Montréal, Québec, Canada",Downtown Montreal,Ville-Marie,Montreal,Canada,CA,Point,"[-73.57639, 45.49663]",True
5552,"Porto, Porto, Portugal",,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,"[-8.61693, 41.15137]",False
5553,"Bondi Beach, NSW, Australia",Bondi,Waverley,Sydney,Australia,AU,Point,"[151.26542, -33.89298]",False
5554,"Porto, Porto, Portugal",,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,"[-8.60622, 41.15127]",True

In [9]:
# df_availability => 5555 * 4 columns

df_availability = pd.json_normalize(df["availability"])
df_availability

      availability_30  availability_60  availability_90  availability_365
0                   7               19               33               118
1                  20               29               29                34
2                  30               60               90               365
3                  30               60               87               359
4                   0                0                0                 0
...               ...              ...              ...               ...
5550               30               60               90               365
5551               29               59               89                89
5552               26               51               77               300
5553                0                0                0                 0
5554               28               54               82               351

[5555 rows x 4 columns]

In [10]:
# df_review_scores => 5555 * 7 columns

df_review_scores = pd.json_normalize(df["review_scores"])
df_review_scores

,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,10.0,10.0,10.0,10.0,10.0,10.0,98.0
1,10.0,10.0,10.0,10.0,9.0,10.0,95.0
2,9.0,9.0,10.0,10.0,10.0,9.0,92.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10.0,9.0,10.0,10.0,10.0,9.0,95.0
...,...,...,...,...,...,...,...
5550,10.0,10.0,10.0,10.0,10.0,10.0,100.0
5551,10.0,10.0,10.0,10.0,10.0,10.0,99.0
5552,10.0,10.0,10.0,10.0,10.0,10.0,98.0
5553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9.0,9.0,9.0,9.0,9.0,8.0,89.0

In [11]:
df.drop(["host","address","availability","review_scores"],axis=1,inplace=True)

In [12]:
# concat_df => 5555 * 74 columns

concat_df = pd.concat([df, df_host,df_address,df_availability,df_review_scores],axis=1)
concat_df

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,availability_60,availability_90,availability_365,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,10038496,https://www.airbnb.com/rooms/10038496,Copacabana Apartment Posto 6,"The Apartment has a living room, toilet, bedro...","The apartment has a living room, wash room, su...","The Apartment has a living room, toilet, bedro...",Copacabana in the South zone is the district t...,,On the street there is plenty of transport and...,todo o espaço.,...,19,33,118,10.0,10.0,10.0,10.0,10.0,10.0,98.0
1,10140368,https://www.airbnb.com/rooms/10140368,A bedroom far away from home,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...",our place is a good sized apartment in a very ...,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...","our neighborhood is basically peaceful, there ...",,subway is about 5-8 minutes away by foot. ther...,you can use the living room and kitchen. we al...,...,29,29,34,10.0,10.0,10.0,10.0,9.0,10.0,95.0
2,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,60,90,365,9.0,9.0,10.0,10.0,10.0,9.0,92.0
3,10112159,https://www.airbnb.com/rooms/10112159,Downtown Oporto Inn (room cleaning),"Tradicional building, with high ceilings next ...","Cozy, located near the most interesting points...","Tradicional building, with high ceilings next ...","Exciting, urban and dinamic, stay with us, nea...",No private parking.,"Next to Trindade subway station, and also to F...","It is a Inn with groundfloor and 1st floor, wi...",...,60,87,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,0,0,0,10.0,9.0,10.0,10.0,10.0,9.0,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9951865,https://www.airbnb.com/rooms/9951865,Quarto Legal,"Meu espaço é perto de Cristo Redentor, Copacab...","Sala, cozinha, áreas comuns do prédio. Caso o ...","Meu espaço é perto de Cristo Redentor, Copacab...","Gosto de morar aqui, e tranquilo ,tem acesso a...",No nossa condomínio possuímos sala de jogos sê...,"Os hóspedes podem se locomover de ônibus, metr...","Podem usar a sala , cozinha , banheiro e a aca...",...,60,90,365,10.0,10.0,10.0,10.0,10.0,10.0,100.0
5551,9907103,https://www.airbnb.com/rooms/9907103,Brand New Luxury Downtown Studio,Perfectly located on the very famous Crescent ...,Perfectly located on the very famous Crescent ...,Perfectly located on the very famous Crescent ...,,,,,...,59,89,89,10.0,10.0,10.0,10.0,10.0,10.0,99.0
5552,9983221,https://www.airbnb.com/rooms/9983221,Cozy apartment downtown Porto,"Renovated, fully equipped, within walking dist...",Very confortable apartment. Ideal for a long w...,"Renovated, fully equipped, within walking dist...",Just in the street 50 meters from the apartmen...,The apartment is in the 2nd floor without elev...,You have the metro nearby (Lapa Station) the w...,The whole apartment.,...,51,77,300,10.0,10.0,10.0,10.0,10.0,10.0,98.0
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,,A bright large double room is available in a b...,,,The flat is exactly half way between the shops...,"Guests will have access to the full residence,...",...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9917859,https://www.airbnb.com/rooms/9917859,StayIN Oporto Música - Apartment,Acabamos de decorar-lo para receber os primeir...,,Acabamos de decorar-lo para receber os primeir...,,,,,...,54,82,351,9.0,9.0,9.0,9.0,9.0,8.0,89.0

In [13]:
# Filling Nan values as 0

concat_df["bedrooms"] = concat_df["bedrooms"].fillna(0)
concat_df["beds"] = concat_df["beds"].fillna(0)
concat_df["bathrooms"] = concat_df["bathrooms"].fillna(0)
concat_df["host_response_rate"] = concat_df["host_response_rate"].fillna(0)

In [14]:
# reviews_count --> 0 : All values of review_score columns become NaN

concat_df[concat_df["number_of_reviews"]==0][['review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value',
       'review_scores_rating',"number_of_reviews","reviews_per_month"]]

,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating,number_of_reviews,reviews_per_month
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...
5536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
5544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
5545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
5548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
5553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [15]:
# is_reviewed --> new column added - 0 : not reviewed & 1 : reviewed
# concat_df => 5555 * 75 columns

concat_df["is_reviewed"] = np.where(concat_df["number_of_reviews"] == 0, 0,1)
concat_df.head(5)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,availability_90,availability_365,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating,is_reviewed
0,10038496,https://www.airbnb.com/rooms/10038496,Copacabana Apartment Posto 6,"The Apartment has a living room, toilet, bedro...","The apartment has a living room, wash room, su...","The Apartment has a living room, toilet, bedro...",Copacabana in the South zone is the district t...,,On the street there is plenty of transport and...,todo o espaço.,...,33,118,10.0,10.0,10.0,10.0,10.0,10.0,98.0,1
1,10140368,https://www.airbnb.com/rooms/10140368,A bedroom far away from home,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...",our place is a good sized apartment in a very ...,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...","our neighborhood is basically peaceful, there ...",,subway is about 5-8 minutes away by foot. ther...,you can use the living room and kitchen. we al...,...,29,34,10.0,10.0,10.0,10.0,9.0,10.0,95.0,1
2,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,90,365,9.0,9.0,10.0,10.0,10.0,9.0,92.0,1
3,10112159,https://www.airbnb.com/rooms/10112159,Downtown Oporto Inn (room cleaning),"Tradicional building, with high ceilings next ...","Cozy, located near the most interesting points...","Tradicional building, with high ceilings next ...","Exciting, urban and dinamic, stay with us, nea...",No private parking.,"Next to Trindade subway station, and also to F...","It is a Inn with groundfloor and 1st floor, wi...",...,87,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,0,0,10.0,9.0,10.0,10.0,10.0,9.0,95.0,1

In [16]:
# Using conditional statements directly in apply -- Categorizing "review_scores_rating" into 5 categories => new column added
# concat_df => 5555 * 76 columns
concat_df['rating_category'] = concat_df['review_scores_rating'].apply(lambda x: 'Poor' if x>0 and x<=20 
                                                                        else 'Needs Improvement' if x>20 and x<=40
                                                                        else 'Meets Expectations' if x>40 and x<=60 
                                                                        else 'Exceeds Expectations' if x>60 and x<=80 
                                                                        else 'Outstanding')

In [17]:
# Defining a function to categorize "Availabiity" into 5 categories => new column added
#concat_df => 5555 * 77 columns

def availability(row):
    if row["availability_365"]==0:
        return "Booked for a year"
    elif row["availability_90"]==0:
        return "Booked for 3 months"
    elif row["availability_60"]==0:
        return "Booked for 2 months"
    elif row["availability_30"]==0:
        return "Booked for a month"
    else:
        return "Bookings Available"
concat_df["Availability"] = concat_df.apply(lambda row: availability(row),axis=1)

In [18]:
# As "is_reviwed" column can be used to filter data -- Nan values of review_score column can be filled with 0

concat_df["review_scores_accuracy"] = concat_df["review_scores_accuracy"].fillna(0)
concat_df["review_scores_cleanliness"] = concat_df["review_scores_cleanliness"].fillna(0)
concat_df["review_scores_checkin"] = concat_df["review_scores_checkin"].fillna(0)
concat_df["review_scores_communication"] = concat_df["review_scores_communication"].fillna(0)
concat_df["review_scores_location"] = concat_df["review_scores_location"].fillna(0)
concat_df["review_scores_value"] = concat_df["review_scores_value"].fillna(0)
concat_df["review_scores_rating"] = concat_df["review_scores_rating"].fillna(0)
concat_df["reviews_per_month"] = concat_df["reviews_per_month"].fillna(0)

In [19]:
# Converting data types of other required columns

concat_df["minimum_nights"] = concat_df["minimum_nights"].astype(int)
concat_df["maximum_nights"] = concat_df["maximum_nights"].astype(int)
concat_df["last_scraped"] = pd.to_datetime(concat_df["last_scraped"])
concat_df["calendar_last_scraped"] = pd.to_datetime(concat_df["calendar_last_scraped"])
concat_df["first_review"] = pd.to_datetime(concat_df["first_review"])
concat_df["last_review"] = pd.to_datetime(concat_df["last_review"])
concat_df["bedrooms"] = concat_df["bedrooms"].astype(int)
concat_df["beds"] = concat_df["beds"].astype(int)
concat_df["bathrooms"] = concat_df["bathrooms"].astype(int)
concat_df["host_response_rate"] = concat_df["host_response_rate"].astype(int)
concat_df["host_listings_count"] = concat_df["host_listings_count"].astype(int)
concat_df["host_total_listings_count"] = concat_df["host_total_listings_count"].astype(int)
concat_df["availability_30"]=concat_df["availability_30"].astype(int)
concat_df["availability_60"]=concat_df["availability_60"].astype(int)
concat_df["availability_90"]=concat_df["availability_90"].astype(int)
concat_df["availability_365"]=concat_df["availability_365"].astype(int)
concat_df["review_scores_accuracy"]=concat_df["review_scores_accuracy"].astype(int)
concat_df["review_scores_cleanliness"]=concat_df["review_scores_cleanliness"].astype(int)
concat_df["review_scores_checkin"]=concat_df["review_scores_checkin"].astype(int)
concat_df["review_scores_communication"]=concat_df["review_scores_communication"].astype(int)
concat_df["review_scores_location"]=concat_df["review_scores_location"].astype(int)
concat_df["review_scores_value"]=concat_df["review_scores_value"].astype(int)
concat_df["review_scores_rating"]=concat_df["review_scores_rating"].astype(int)
concat_df["reviews_per_month"]=concat_df["reviews_per_month"].astype(int)

In [20]:
concat_df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating,is_reviewed,rating_category,Availability
0,10038496,https://www.airbnb.com/rooms/10038496,Copacabana Apartment Posto 6,"The Apartment has a living room, toilet, bedro...","The apartment has a living room, wash room, su...","The Apartment has a living room, toilet, bedro...",Copacabana in the South zone is the district t...,,On the street there is plenty of transport and...,todo o espaço.,...,10,10,10,10,10,10,98,1,Outstanding,Bookings Available
1,10140368,https://www.airbnb.com/rooms/10140368,A bedroom far away from home,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...",our place is a good sized apartment in a very ...,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...","our neighborhood is basically peaceful, there ...",,subway is about 5-8 minutes away by foot. ther...,you can use the living room and kitchen. we al...,...,10,10,10,10,9,10,95,1,Outstanding,Bookings Available
2,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,9,9,10,10,10,9,92,1,Outstanding,Bookings Available
3,10112159,https://www.airbnb.com/rooms/10112159,Downtown Oporto Inn (room cleaning),"Tradicional building, with high ceilings next ...","Cozy, located near the most interesting points...","Tradicional building, with high ceilings next ...","Exciting, urban and dinamic, stay with us, nea...",No private parking.,"Next to Trindade subway station, and also to F...","It is a Inn with groundfloor and 1st floor, wi...",...,0,0,0,0,0,0,0,0,Outstanding,Bookings Available
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,10,9,10,10,10,9,95,1,Outstanding,Booked for a year

In [21]:
concat_df.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month', 'host_id', 'host_url',
       'host_name', 'host_location', 'host_about', 'host_response_time',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_response_rate', 'host_is_superhost', 'host_has_profile_pic',
       'host_identity_verified', 'host_listings_count',
       'host_total_listings_count', 'host_verifications', 'street', 'suburb',
       'government_area', 'market', 'country', 'country_code', 'location.type',
       'location.coordinates', 'location.is_location_exact', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'review_scores_rating',
       'is_reviewed', 'rating_category', 'Availability'],
      dtype='object')

In [52]:
def filter_country(country):
        filtered_df = concat_df[(concat_df["country"]==country)]
        filtered_df.reset_index(drop=True, inplace=True)
        return filtered_df

In [23]:
def filter_market(df,market):
        filtered_df = df[(df["market"]==market)]
        filtered_df.reset_index(drop=True, inplace=True)
        return filtered_df

In [44]:
def filter_reviewed(df):
        filtered_df = df[(df["is_reviewed"]==1)]
        filtered_df.reset_index(drop=True, inplace=True)
        return filtered_df

In [25]:
def filter_host_id(df,host_id):
        filtered_df = df[(df["host_id"]==host_id)]
        filtered_df.reset_index(drop=True, inplace=True)
        return filtered_df

In [26]:
def view_listed_properties(host_id):
    df = concat_df[concat_df["host_id"]==host_id]
    new_df = df[["_id","name","country","Availability","number_of_reviews","review_scores_rating","first_review","last_review"]].reset_index(drop=True)
    st.write(new_df)

In [27]:
# Overview 

def overview():
    grouped_country_df = concat_df.groupby("country").agg(Number_of_properties_listed=('_id','count')).reset_index()
    mappings = {"Australia" : "AUS",
                "Brazil" : "BRA",
                "Canada" : "CAN",
                "China" : "CHN",
                "Hong Kong" : "HKG",
                "Portugal" : "PRT",
                "Spain" : "ESP",
                "Turkey" : "TUR",
                "United States" : "USA"}
    grouped_country_df["iso_code"] = grouped_country_df["country"].map(mappings)
    color_map = {'Australia': 'blue',
                'Brazil': 'green',
                'Canada': 'red',
                'China': 'purple',
                'Hong Kong': 'orange',
                'Portugal': 'cyan',
                'Spain': 'magenta',
                'Turkey': 'yellow',
                'United States': 'lime'}
    fig_map = px.scatter_geo(grouped_country_df, locations="iso_code",
                        size="Number_of_properties_listed", projection='natural earth',color='country',color_discrete_map=color_map)
    fig_map.update_geos(showcoastlines=True, coastlinecolor="Black", showland=True, landcolor="White",
                    showocean=True, oceancolor="LightBlue", showcountries=True, countrycolor="Gray")
    fig_map.show()

    # Country Wise
    fig_box_country = px.box(concat_df, x='country', y='price', points=False, title='Country vs Price')

    fig_box_country.update_layout(xaxis_title='Country', yaxis_title='Price', title_x=0.5, boxmode='group')
    fig_box_country.update_yaxes(range=[10,1000])
    fig_box_country.show() 

    # Market Wise
    fig_box_market = px.box(concat_df, x='market', y='price', points=False, title='Market Vs Price')

    fig_box_market.update_layout(xaxis_title='Market', yaxis_title='Price', title_x=0.5, boxmode='group')
    fig_box_market.update_yaxes(range=[10,1000])
    fig_box_market.show()

In [28]:
# Plots for high in demand 

def in_demand(df):
    # Preferred Bed Type
    grouped_bed_df = df.groupby(["bed_type","Availability"]).agg(Number_of_properties=('_id', 'count')).reset_index()
    custom_order = ['Booked for a year', 'Booked for 3 months', 'Booked for 2 months', 'Booked for a month','Bookings Available']
    grouped_bed_df_sorted = grouped_bed_df.set_index('Availability').loc[custom_order].reset_index()
    fig_bar_bed_type = px.bar(grouped_bed_df_sorted, x="bed_type",y="Number_of_properties",title="Preferred Bed Type",color="Availability",barmode="stack",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_bed_type.update_layout(xaxis_title=None)
    fig_bar_bed_type.show()
    # Preferred Room Type
    grouped_room_df = df.groupby(["room_type","Availability"]).agg(Number_of_properties=('_id', 'count')).reset_index()
    custom_order = ['Booked for a year', 'Booked for 3 months', 'Booked for 2 months', 'Booked for a month','Bookings Available']
    grouped_room_df_sorted = grouped_room_df.set_index('Availability').loc[custom_order].reset_index()
    fig_sunburst_room_type = px.sunburst(grouped_room_df_sorted, path=['room_type','Availability'], values='Number_of_properties',
                    title='Preferred Room Type',color='Availability',color_discrete_sequence=px.colors.qualitative.Plotly)
    fig_sunburst_room_type.update_layout(xaxis_title=None)
    fig_sunburst_room_type.show()
    # Preferred Property Type
    grouped_prop_df = df.groupby(["property_type","Availability"]).agg(Number_of_properties=('_id', 'count')).reset_index()
    custom_order = ['Booked for a year', 'Booked for 3 months', 'Booked for 2 months', 'Booked for a month','Bookings Available']
    grouped_prop_df_sorted = grouped_prop_df.set_index('Availability').loc[custom_order].reset_index()
    fig_bar_prop_type = px.bar(grouped_prop_df_sorted, x="property_type",y="Number_of_properties",title="Preferred Property Type",color="Availability",barmode="stack",
                            width=1100, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_prop_type.update_layout(xaxis_title=None)
    fig_bar_prop_type.show()
    # Preferred Cancellation Policy
    grouped_cancelp_df = df.groupby(["cancellation_policy","Availability"]).agg(Number_of_properties=('_id', 'count')).reset_index()
    custom_order = ['Booked for a year', 'Booked for 3 months', 'Booked for 2 months', 'Booked for a month','Bookings Available']
    grouped_cancelp_df_sorted = grouped_cancelp_df.set_index('Availability').loc[custom_order].reset_index()
    fig_bar_cancelp_type = px.bar(grouped_cancelp_df_sorted, x="cancellation_policy",y="Number_of_properties",title="Preferred Cancellation Policy",color="Availability",barmode="stack",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_cancelp_type.update_layout(xaxis_title=None)
    fig_bar_cancelp_type.show()

In [29]:
# Plots for reviewed and rated
def top_rated(df):
    concat_df_reviewed = filter_reviewed(df)

    # Average Rating of different Bed Types
    grouped_bed_df = concat_df_reviewed.groupby(["bed_type","rating_category"]).agg(Average_Rating=('review_scores_rating','mean')).reset_index()
    grouped_bed_df["Average_Rating"] = round(grouped_bed_df["Average_Rating"],2)
    custom_order = ['Poor', 'Needs Improvement', 'Meets Expectations', 'Exceeds Expectations','Outstanding']
    grouped_bed_df_sorted = grouped_bed_df.set_index('rating_category').loc[custom_order].reset_index()
    fig_bar_bed_type = px.bar(grouped_bed_df_sorted, x="rating_category",y="Average_Rating",title="Average Rating of different Bed Types",color="bed_type",barmode="group",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_bed_type.show()
    # Average Rating of different Room Types
    grouped_room_df = concat_df_reviewed.groupby(["room_type","rating_category"]).agg(Average_Rating=('review_scores_rating','mean')).reset_index()
    grouped_room_df["Average_Rating"] = round(grouped_room_df["Average_Rating"],2)
    custom_order = ['Poor', 'Needs Improvement', 'Meets Expectations', 'Exceeds Expectations','Outstanding']

    grouped_room_df_sorted = grouped_room_df.set_index('rating_category').loc[custom_order].reset_index()
    fig_bar_room_type = px.bar(grouped_room_df_sorted, x="rating_category",y="Average_Rating",title="Average Rating of different Room Types",color="room_type",barmode="group",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_room_type.show()
    # Average Rating of Top 3 Property Types
    def select_top_n(df, n=2):
        return df.sort_values(by='Average_Rating', ascending=False).head(n)
    grouped_prop_df = concat_df_reviewed.groupby(["property_type","rating_category"]).agg(Average_Rating=('review_scores_rating','mean')).reset_index()
    grouped_prop_df["Average_Rating"] = round(grouped_prop_df["Average_Rating"],2)
    top_n_property_types = grouped_prop_df.groupby('rating_category', group_keys=False).apply(select_top_n, n=3).reset_index(drop=True)
    custom_order = ['Poor', 'Needs Improvement', 'Meets Expectations', 'Exceeds Expectations','Outstanding']
    # Sort DataFrame based on custom_order
    top_n_property_types_sorted = top_n_property_types.set_index('rating_category').loc[custom_order].reset_index()
    fig_bar_prop_type = px.bar(top_n_property_types_sorted, x="rating_category",y="Average_Rating",title="Average Rating of Top 3 Property Types",color="property_type",barmode="group",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_prop_type.show()

In [30]:
top_properties_df = concat_df[(concat_df["Availability"]=="Booked for a year") & (concat_df["rating_category"]=="Outstanding")].reset_index(drop=True)
min_nights = top_properties_df['minimum_nights'].mean()
max_nights = top_properties_df['maximum_nights'].mean()

In [31]:
# Other Features Preferred 

def get_other_preferred_features():
    top_properties_df = concat_df[(concat_df["Availability"]=="Booked for a year") & (concat_df["rating_category"]=="Outstanding")].reset_index(drop=True)
    
    aminities = []
    top_aminities = []
    for i in range(len(top_properties_df)):
        for j in top_properties_df["amenities"][i]:
            aminities.append(j)
    # Count occurrences of each item in the list
    item_counts = Counter(aminities)

    # Get the top 10 most common items
    top_10_items = item_counts.most_common(10)
    
    col1, col2 = st.columns(2)
    with col1:
        # Print the top 10 items and their counts
        for item, count in top_10_items:
            print(f"{item}")
    with col2:
        st.write("Limit of Minimum Nights preferred by Customers : ",top_properties_df['minimum_nights'].mean())
        st.write("Limit of Maximum Nights preferred by Customers : ",top_properties_df['maximum_nights'].mean())
    fig_box_features = px.box(top_properties_df, y=['bedrooms','beds','bathrooms','accommodates','guests_included'],points=False)
    fig_box_features.update_yaxes(range=[0,7]) 
    fig_box_features.show()

In [32]:
# Pricing Dynamics 

country = concat_df["country"].unique().tolist()
property_type = concat_df["property_type"].unique().tolist()
room_type = concat_df["room_type"].unique().tolist()
number_of_bedrooms = concat_df["bedrooms"].unique().tolist()
bed_type = concat_df["bed_type"].unique().tolist()
number_of_beds = concat_df["beds"].unique().tolist()
number_of_accommodates = concat_df["accommodates"].unique().tolist()
number_of_guests = concat_df["guests_included"].unique().tolist()

def prop_price(property_type):
    filtered_df = concat_df[concat_df["property_type"]==property_type]
    grouped_df = filtered_df[["country","price"]].groupby("country")["price"].mean().reset_index()
    fig_bar_prop_type = px.bar(grouped_df, x="country",y="price",title=f"Average price by Country for {property_type}",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_prop_type.show()

def room_price(room_type,number_of_bedrooms):
    filtered_df = concat_df[(concat_df["room_type"]==room_type) & (concat_df["bedrooms"]==number_of_bedrooms)]
    grouped_df = filtered_df[["country","price"]].groupby("country")["price"].mean().reset_index()
    fig_bar_room_type = px.bar(grouped_df, x="country",y="price",title=f"Average price by Country for {number_of_bedrooms} {room_type}",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_room_type.show()

def bed_price(bed_type,number_of_beds):
    filtered_df = concat_df[(concat_df["bed_type"]==bed_type) & (concat_df["beds"]==number_of_beds)]
    grouped_df = filtered_df[["country","price"]].groupby("country")["price"].mean().reset_index()
    fig_bar_bed_type = px.bar(grouped_df, x="country",y="price",title=f"Average price by Country for {number_of_bedrooms} {bed_type}",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_bed_type.show()

def acc_price(number_of_accommodates,number_of_guests):
    filtered_df = concat_df[(concat_df["accommodates"]==number_of_accommodates) & (concat_df["guests_included"]==number_of_guests)]
    grouped_df = filtered_df[["country","price"]].groupby("country")["price"].mean().reset_index()
    fig_bar_acc_type = px.bar(grouped_df, x="country",y="price",title=f"Price by Country for {number_of_accommodates} accommodates and {number_of_guests} guests",
                            width=1000, color_discrete_sequence=px.colors.sequential.Aggrnyl_r)
    fig_bar_acc_type.show()

In [33]:
# For reference 

grouped_host_df = concat_df.groupby("host_id").agg(Number_of_properties_listed=('_id','count')).reset_index()
grouped_host_df[grouped_host_df["Number_of_properties_listed"] == 7]

       host_id  Number_of_properties_listed
2833  30907275                            7
3244   3953109                            7

In [37]:
concat_df.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month', 'host_id', 'host_url',
       'host_name', 'host_location', 'host_about', 'host_response_time',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_response_rate', 'host_is_superhost', 'host_has_profile_pic',
       'host_identity_verified', 'host_listings_count',
       'host_total_listings_count', 'host_verifications', 'street', 'suburb',
       'government_area', 'market', 'country', 'country_code', 'location.type',
       'location.coordinates', 'location.is_location_exact', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'review_scores_rating',
       'is_reviewed', 'rating_category', 'Availability'],
      dtype='object')

In [ ]:
top_properties_df = concat_df[(concat_df["Availability"]=="Booked for a year") & (concat_df["rating_category"]=="Outstanding")].reset_index(drop=True)
top_properties_df[top_properties_df["review_scores_rating"]==100]

In [ ]:
concat_df.columns

In [79]:
concat_df.head(2)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating,is_reviewed,rating_category,Availability
0,10038496,https://www.airbnb.com/rooms/10038496,Copacabana Apartment Posto 6,"The Apartment has a living room, toilet, bedro...","The apartment has a living room, wash room, su...","The Apartment has a living room, toilet, bedro...",Copacabana in the South zone is the district t...,,On the street there is plenty of transport and...,todo o espaço.,...,10,10,10,10,10,10,98,1,Outstanding,Bookings Available
1,10140368,https://www.airbnb.com/rooms/10140368,A bedroom far away from home,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...",our place is a good sized apartment in a very ...,"NOTES: BEFORE BOOKING, PLEASE KNOW THAT WE ARE...","our neighborhood is basically peaceful, there ...",,subway is about 5-8 minutes away by foot. ther...,you can use the living room and kitchen. we al...,...,10,10,10,10,9,10,95,1,Outstanding,Bookings Available

In [85]:
excel_file_path = "Airbnb_Data.xlsx"
concat_df.to_excel(excel_file_path, index=False)

In [ ]:
import streamlit as st
import webbrowser

def main():
    st.title('URL Navigation Button')

    # Define a function to open the URL in a new tab
    def open_url_in_new_tab(url):
        webbrowser.open_new_tab(url)

# Create a button with a label and a callback function
if st.button('Dashboard'):
    url = 'https://www.google.com'
    open_url_in_new_tab(url)

if __name__ == '__main__':
    main()

In [ ]:
import streamlit as st
import webbrowser

def main():
    st.title('URL Navigation Button')

    # Define a function to open the URL in a new tab
    def open_url_in_new_tab(url):
        webbrowser.open_new_tab(url)

    # Create a button with a label and a callback function
    if st.button('Dashboard'):
        url = 'https://public.tableau.com/views/Airbnb_Dashboard_17212423837350/Dashboard1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link'
        open_url_in_new_tab(url)

if __name__ == '__main__':
    main()